Digital_Schoolhouse/config/routes.rb
DigitalSchoolhouse::Application.routes.draw do
  resources :attachments

  resources :posts

  resources :users

  resources :schools
  
  root :to => "posts#index"

end

Digital_Schoolhouse/app/models/post.rb
class Post < ActiveRecord::Base
end

Digital_Schoolhouse/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

Digital_Schoolhouse/app/helpers/posts_helper.rb
module PostsHelper
end

Digital_Schoolhouse/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_date %><br />
    <%= f.number_field :post_date %>
  </div>
  <div class="field">
    <%= f.label :published %><br />
    <%= f.check_box :published %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :attachments_id %><br />
    <%= f.number_field :attachments_id %>
  </div>
  <div class="field">
    <%= f.label :tags %><br />
    <%= f.text_area :tags %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_area :slug %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Digital_Schoolhouse/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

Digital_Schoolhouse/app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Post date</th>
    <th>Published</th>
    <th>Title</th>
    <th>Body</th>
    <th>Attachments</th>
    <th>Tags</th>
    <th>User</th>
    <th>Slug</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.post_date %></td>
    <td><%= post.published %></td>
    <td><%= post.title %></td>
    <td><%= post.body %></td>
    <td><%= post.attachments_id %></td>
    <td><%= post.tags %></td>
    <td><%= post.user_id %></td>
    <td><%= post.slug %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

Digital_Schoolhouse/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

Digital_Schoolhouse/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Post date:</b>
  <%= @post.post_date %>
</p>

<p>
  <b>Published:</b>
  <%= @post.published %>
</p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Body:</b>
  <%= @post.body %>
</p>

<p>
  <b>Attachments:</b>
  <%= @post.attachments_id %>
</p>

<p>
  <b>Tags:</b>
  <%= @post.tags %>
</p>

<p>
  <b>User:</b>
  <%= @post.user_id %>
</p>

<p>
  <b>Slug:</b>
  <%= @post.slug %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>