Digital_Schoolhouse/config/routes.rb
DigitalSchoolhouse::Application.routes.draw do
  resources :attachments

  resources :posts

  resources :users

  resources :schools
  
  root :to => "posts#index"

end

Digital_Schoolhouse/app/models/school.rb
class School < ActiveRecord::Base
end

Digital_Schoolhouse/app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schools }
    end
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    @school = School.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/new
  # GET /schools/new.json
  def new
    @school = School.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/1/edit
  def edit
    @school = School.find(params[:id])
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(params[:school])

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render json: @school, status: :created, location: @school }
      else
        format.html { render action: "new" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schools/1
  # PUT /schools/1.json
  def update
    @school = School.find(params[:id])

    respond_to do |format|
      if @school.update_attributes(params[:school])
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school = School.find(params[:id])
    @school.destroy

    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end
end

Digital_Schoolhouse/app/helpers/schools_helper.rb
module SchoolsHelper
end

Digital_Schoolhouse/app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Digital_Schoolhouse/app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

Digital_Schoolhouse/app/views/schools/index.html.erb
<h1>Listing schools</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Country</th>
    <th>State</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @schools.each do |school| %>
  <tr>
    <td><%= school.name %></td>
    <td><%= school.country %></td>
    <td><%= school.state %></td>
    <td><%= link_to 'Show', school %></td>
    <td><%= link_to 'Edit', edit_school_path(school) %></td>
    <td><%= link_to 'Destroy', school, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New School', new_school_path %>

Digital_Schoolhouse/app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

Digital_Schoolhouse/app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @school.name %>
</p>

<p>
  <b>Country:</b>
  <%= @school.country %>
</p>

<p>
  <b>State:</b>
  <%= @school.state %>
</p>


<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>